server:
  port: 8090  #Spring boot Server port

spring:
    datasource:
      driver-class-name: org.h2.Driver # h2 database setting
      # url: 'jdbc:h2:mem:test' # In-memory mode
      url: 'jdbc:h2:localhost/~./test'  # Embedded Mode
      username: sa
      password:
   # h2 console setting
    h2:
      console:
        enabled: true
        path: /h2-console

  # boot: DataSource 의 스키마를 schema.sql 로 생성 / data.sql 로 초기화
    jpa:
      hibernate:
        ddl-auto: update # entity class tb로 자동 생성 - test 시만 사용
       # format_sql: true
        show_sql: true #jpa 실행 시 sql 로그에 출력
